uses: vortegon/github-action-ansible-tower@v1
with:
  ansible-tower-user: ${{ secrets.ansibleUser }}
  ansible-tower-pass: ${{ secrets.ansiblePass }}
  ansible-tower-url: ${{ secrets.ansibleUrl }}
  template-id: "98"
  additional-vars: |
  {
      "var_azure_rm_subid": "${{ secrets.azureSubscription }}",
    }
  
