on:
  # Allows you to run this workflow manually from the Actions tab
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Call Controller to start Job
       uses: fitbeard/action-trigger-awx@v22.7.0
       with:
         tower_url: ${{ secrets.ANSIBLEURL }}
         tower_token: ${{ secrets.ANSIBLEKEY}}
         tower_verify_ssl: false
         resource_type: job_template
         resource_name: 98
         extra_vars: '{"file2comp": hosts}'



