on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Call Controller to start Job
       uses: dkershner6/post-api-call-action@v1
       with:
         url: ${{ secrets.ANSIBLEURL }}
         headers: "{\"Authorization\": \"Bearer ${{ secrets.ANSIBLEKEY}}\"}"
  




