uses: vortegon/github-action-ansible-tower@v1
with:
  ansible-tower-user: ${{ ansibleUser }}
  ansible-tower-pass: ${{ ansiblePass }}
  ansible-tower-url: ${{ ansibleUrl }}
  template-id: "98"
  additional-vars: |
  {
      "var_azure_rm_subid": "${{ azureSubscription }}",
    }
  
